# Build (Linux)

version: "3"
services:

  # stage:
  #   build:
  #     context: ../
  #     dockerfile: ./build/stage_linux.docker
  #   image: "swashbuckle_stage:linux"

  build:
    build:
      context: ../
      dockerfile: ./build/build_linux.docker
      args:
        stage_image: "swashbuckle_stage:linux" 
    image: "rogersantos/swashbuckle:linux"
    # depends_on: 
    #   - stage
    # entrypoint: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - "8080:80"

